config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :brands
  resources :productcategories
  resources :testimonials
  get 'admin/index'
  get 'admin/admin_new'
  post "admin_create" => "admin#admin_create", :as => :admin_create 
  get 'admin/user_new'
  get 'admin/orders_index'
  post "user_create" => "admin#user_create", :as => :user_create 
   get 'home/products/:id' => "home#products", :as => :home_product
  get "product_desc/:id" => "home#product_desc", :as => :product_desc
  get 'home/shipingAddress'
  get 'home/contact_us'
  post 'home/create_contactus'
  get 'home/mobiles'
  get 'home/computers'
  get 'home/product_sucess'
  post 'home/statuscreate'
  get "mobile_desc/:id" => "home#mobile_desc", :as => :mobile_desc
  get "computer_desc/:id" => "home#computer_desc", :as => :computer_desc
  get "cartdel/:id" => "home#cartdel", :as => :cartdel
   get 'admin/admin_index'
   get 'admin/user_index'
   get 'home/checkout'
   get 'home/deals'
   get 'home/cartcreate'

   root 'home#index'
   get '/signup' => 'users#new'
    post '/users' => 'users#create'

  get '/login' => 'users#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/views/admin/admin_index.html.erb
<section class="content-header">
	<h1>Admin</h1>
</section>
<section class="content">
	<div class="text-centre"><%= link_to "Add New Admin",admin_admin_new_path,:class => "btn btn-primary"%></div><br/>
	<div class="row">
		<div class="col-xs-12">
			<div class="box">

				<div class="box-body table-responsive">
					<table id="example1" class="table table-bordered table-striped">
						<thead>
							<tr>
								<th>Sr.No.</th>
								<th>Name</th>
								<th>Email</th>
								<!-- <th></th> -->
							</tr>	
						</thead>
						<% @count = 0 %>
						<% @users.each do |user|%>
						<tbody>
							<tr>
								<% @count += 1 %>
								<td><%=  @count %></td>
								<td><%= user.name %></td>
								<td><%= user.email %></td>
								<!-- <td>
									<%#= link_to "<i class='glyphicon glyphicon-eye-open'></i>".html_safe,  admin_admin_show_path(user.id),:class => " btn btn-default btn-xs" %>
									<%#= link_to "<i class='glyphicon glyphicon-pencil'></i>".html_safe, admin_admin_edit_path(user),:class => " btn btn-default btn-xs" %>
									 <%#= link_to "<i class='glyphicon glyphicon-trash'></i>".html_safe, admin_admin_destroy_path(user.id),  data: { confirm: 'Are you sure?' },method: :delete,:class => " btn btn-default btn-xs" %> 
								</td> -->
							</tr>
						</tbody>
						<% end %>
					</table>

					<% if @users.count > 10 %>
					<br/>
					<div class="digg_pagination">
						<%= will_paginate @users, :container => false %>
					</div>
					<% end %>
				</div>					
			</div>						
		</div>							
	</div>								
</section>

app/views/admin/admin_new.html.erb
<section class="content-header">
    <h1>New Admin</h1>
</section>

<section class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="box box-primary">
				<div class="box-body">
				<%= form_for :user, url: '/admin_create' do |f| %>
              <div class="form-group">
                <label for="exampleInputEmail1">Name</label>
                <%= f.text_field :name, :class =>"form-control", :id =>"exampleInputEmail1", :placeholder =>"Enter Name" %>
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <%= f.text_field :email, :class =>"form-control", :id =>"exampleInputEmail1", :placeholder =>"Enter email" %>
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <%= f.password_field :password , :class =>"form-control", :id =>"exampleInputPassword1", :placeholder =>"Enter Password" %>
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Confirmation Password</label>
                <%= f.password_field :password_confirmation , :class =>"form-control", :id =>"exampleInputPassword1", :placeholder =>"Enter Confirmation Password" %>
              </div>
              <!-- <div class="form-group">
                <label for="exampleInputFile">File input</label>
                <input type="file" id="exampleInputFile">
                <p class="help-block">Example block-level help text here.</p>
              </div> -->
              <!-- <div class="checkbox">
                <label>
                  <input type="checkbox"> Check me out
                </label>
              </div> -->
              <%= f.hidden_field :role_id, :value => 1 %>
              <%= f.submit "Submit", :class =>"btn btn-primary" %>
            <%end%>
            </div>

    </div>
			</div>
		</div>
	</div>
</section>

app/views/admin/index.html.erb
<section class="content-header">
	<h1> Dashboard</h1>
</section>

app/views/admin/orders_index.html.erb
<section class="content-header">
  <h1>Listing carts</h1>
</section>
+<section class="content">
  <div class="text-centre"><%#= link_to "Add New cart",new_cart_path,:class => "btn btn-primary"%></div><br/>
  <div class="row">
    <div class="col-xs-12">
      <div class="box">

        <div class="box-body table-responsive">
          <table id="example1" class="table table-bordered table-striped">
            <thead>
              <tr>
                <th>Sr.No.</th>
                <th>Reference Id</th>
                <th>Product</th>
                <th>Product Category</th>
                <th>Buyer Email</th>
                <th>Price</th>
                <th>Status</th>
                <!-- <th>Image</th> -->
                
              </tr> 
            </thead>
            <% @count = 0 %>
            <% @carts.each do |cart|%>
            <tbody>
              <tr>
                <% @count += 1 %>
                <td><%= @count%></td>
                <td><%= cart.tran_id %></td>
                <td><%= Product.find(cart.product_id).name %></td>
                <td><%= Productcategory.find(cart.product_category).name %></td>
                <td><%=User.find(cart.user_id).email%></td>
                <td><%= Product.find(cart.product_id).price%></td>
                <td><%= cart.status %>
                <%= link_to "<i class='glyphicon glyphicon-pencil'></i>".html_safe, 'javascript:void(0)',:class => "btn btn-default btn-xs",:id => "edit#{@count}" %>
                <%= form_tag home_statuscreate_path, :id => "status_form#{@count}" do |f| %>
                    <select id="status<%= @count %>" style="display:none;" name="order_status">  
                     <option value="">--select status--</option>
                      <option value="Pending">Pending</option>
                      <option value="Dispatch">Dispatch</option>
                      <option value="Sucess">Sucess</option>
                    </select>
                    <input type="hidden" name="tran_id" id="tran_id" value="<%= cart.tran_id %>">
                <% end %>
                </td>
                <!-- <td> <img src="<%#= cart.image%>"></td> 
                -->

                <td>
                  <%#= link_to "<i class='glyphicon glyphicon-eye-open'></i>".html_safe,  cart_path(cart.id),:class => " btn btn-default btn-xs" %>
                  <%#= link_to "<i class='glyphicon glyphicon-pencil'></i>".html_safe, edit_cart_path(cart),:class => " btn btn-default btn-xs" %>
                  <!-- <%#= link_to "<i class='glyphicon glyphicon-trash'></i>".html_safe, brand_path(cart.id),  data: { confirm: 'Are you sure?' },method: :delete,:class => " btn btn-default btn-xs" %> -->
                </td>
              </tr>
            </tbody>
            <% end %>
          </table>

          <% if @carts.count > 10 %>
          <br/>
          <div class="digg_pagination">
            <%= will_paginate @carts, :container => false %>
          </div>
          <% end %>
        </div>          
      </div>            
    </div>              
  </div>                
</section>
<script type="text/javascript">
  $(document).ready(function(){
      <% (1..@carts.count).each do |f| %>
        $( "#edit<%= f %>" ).click(function() {
           
            $('#status<%= f %>').show();
        });

        $( "#status<%= f %>" ).change(function() {
            
            $("#status_form<%= f %>").submit();

        });    


      <% end %>
  });
</script>

app/views/admin/user_index.html.erb
<section class="content-header">
	<h1>User</h1>
</section>
<section class="content">
	<div class="text-centre"><%= link_to "Add New User",admin_user_new_path,:class => "btn btn-primary"%></div><br/>
	<div class="row">
		<div class="col-xs-12">
			<div class="box">

				<div class="box-body table-responsive">
					<table id="example1" class="table table-bordered table-striped">
						<thead>
							<tr>
								<th>Sr.No.</th>
								<th>Name</th>
								<th>Email</th>
								<!-- <th></th> -->
							</tr>	
						</thead>
						<% @count = 0 %>
						<% @users.each do |user|%>
						<tbody>
							<tr>
								<% @count += 1 %>
								<td><%=  @count %></td>
								<td><%= user.name %></td>
								<td><%= user.email %></td>
								<!-- <td>
									<%#= link_to "<i class='glyphicon glyphicon-eye-open'></i>".html_safe,  admin_admin_show_path(user.id),:class => " btn btn-default btn-xs" %>
									<%#= link_to "<i class='glyphicon glyphicon-pencil'></i>".html_safe, admin_admin_edit_path(user),:class => " btn btn-default btn-xs" %>
									 <%#= link_to "<i class='glyphicon glyphicon-trash'></i>".html_safe, admin_admin_destroy_path(user.id),  data: { confirm: 'Are you sure?' },method: :delete,:class => " btn btn-default btn-xs" %> 
								</td> -->
							</tr>
						</tbody>
						<% end %>
					</table>

					<% if @users.count > 10 %>
					<br/>
					<div class="digg_pagination">
						<%= will_paginate @users, :container => false %>
					</div>
					<% end %>
				</div>					
			</div>						
		</div>							
	</div>								
</section>

app/views/admin/user_new.html.erb
<section class="content-header">
    <h1>New User</h1>
</section>

<section class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="box box-primary">
      <div class="box-body">
				<%= form_for :user, url: '/user_create' do |f| %>
              <div class="form-group">
                <label for="exampleInputEmail1">Name</label>
                <%= f.text_field :name, :class =>"form-control", :id =>"exampleInputEmail1", :placeholder =>"Enter Name" %>
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <%= f.text_field :email, :class =>"form-control", :id =>"exampleInputEmail1", :placeholder =>"Enter email" %>
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <%= f.password_field :password , :class =>"form-control", :id =>"exampleInputPassword1", :placeholder =>"Enter Password" %>
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Confirmation Password</label>
                <%= f.password_field :password_confirmation , :class =>"form-control", :id =>"exampleInputPassword1", :placeholder =>"Enter Confirmation Password" %>
              </div>
              <!-- <div class="form-group">
                <label for="exampleInputFile">File input</label>
                <input type="file" id="exampleInputFile">
                <p class="help-block">Example block-level help text here.</p>
              </div> -->
              <!-- <div class="checkbox">
                <label>
                  <input type="checkbox"> Check me out
                </label>
              </div> -->
              <%= f.hidden_field :role_id, :value => 2 %>
              <%= f.submit "Submit", :class =>"btn btn-primary" %>
            <%end%>
            </div>
    </div>
			</div>
		</div>
	</div>
</section>