config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :brands
  resources :productcategories
  resources :testimonials
  get 'admin/index'
  get 'admin/admin_new'
  post "admin_create" => "admin#admin_create", :as => :admin_create 
  get 'admin/user_new'
  get 'admin/orders_index'
  post "user_create" => "admin#user_create", :as => :user_create 
   get 'home/products/:id' => "home#products", :as => :home_product
  get "product_desc/:id" => "home#product_desc", :as => :product_desc
  get 'home/shipingAddress'
  get 'home/contact_us'
  post 'home/create_contactus'
  get 'home/mobiles'
  get 'home/computers'
  get 'home/product_sucess'
  post 'home/statuscreate'
  get "mobile_desc/:id" => "home#mobile_desc", :as => :mobile_desc
  get "computer_desc/:id" => "home#computer_desc", :as => :computer_desc
  get "cartdel/:id" => "home#cartdel", :as => :cartdel
   get 'admin/admin_index'
   get 'admin/user_index'
   get 'home/checkout'
   get 'home/deals'
   get 'home/cartcreate'

   root 'home#index'
   get '/signup' => 'users#new'
    post '/users' => 'users#create'

  get '/login' => 'users#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "application"
  before_filter :authorize, only: [:product_desc, :shipingAddress, :statuscreate, :cartcreate]
  def index
    @testimonials = Testimonial.last(3)
  end
  def products 
    if params[:search]
          @products = Product.search(params[:search]).where("product_category_id =?",params[:id]).paginate(:page => params[:page], :per_page => 10)
        else
          @products = Product.where("product_category_id =?",params[:id]).paginate(:page => params[:page], :per_page => 10)

        end

     #@products = Product.where("product_category_id =?",params[:id]).paginate(:page => params[:page], :per_page => 10)
       
  end

  def product_desc 
      @productdesc = Product.find(params[:id])
      

  end


  def shipingAddress

   
    @user = current_user
  	
  end

  def product_sucess
    Cart.where(:tran_id => session[:CART_TEMP_RANDOM]).update_all(:status => "pending")
    session[:CART_TEMP_RANDOM] = nil
    redirect_to root_path, :flash => { :notice => "Order Purchased Sucessfully" }
  end

  def contact_us
    
  end

  def checkout
     @details = Cart.where(:tran_id => session[:CART_TEMP_RANDOM]);

     
  end

  def statuscreate
    Cart.where(:tran_id => params[:tran_id]).update_all(:status => params[:order_status])
    redirect_to admin_orders_index_path
  end

  def deals
    @products = Product.last(6)
    #@computers = Computer.last(3)
  end

  def create_contactus
    contact =  ContactU.new(contact_params)
    if contact.save
    
      UserMailer.contact_email(contact).deliver()
      redirect_to '/'
    else
      render 'contact_us'
    end
    
  end

  def cartcreate

    if session[:CART_TEMP_RANDOM] == nil

       session[:CART_TEMP_RANDOM] = SecureRandom.random_number(1_000_000_000_0)

    end
    
    ranid = session[:CART_TEMP_RANDOM]
      @cart = Cart.new(:product_id => params[:product_id] ,:user_id => params[:user_id],:tran_id => "#{ranid}", :product_category => params[:product_category])
      if @cart.save
        redirect_to home_checkout_path
      end
      # binding.pry

  end

  def cartdel
     Cart.destroy(params[:id]) 
     redirect_to home_checkout_path
  end
  private

  def contact_params
    params.require(:contact).permit(:name, :email, :message)    
  end
  def set_mobile
      @mobile = Mobile.find(params[:id])

    end
  def set_computer
      @computer = Computer.find(params[:id])
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_slider.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <%= image_tag "iPhone-1200x420.jpg"%>
        <div class="carousel-caption">
          <h3 style="  color: rgb(174, 160, 255);font-weight: 900;">Online Shoping Mall</h3>
        </div>      
      </div>

      <div class="item">
        <%= image_tag "s-sleep.jpg"%>
        <div class="carousel-caption">
          <h3 style="color: rgb(240, 39, 62);font-weight: 900;">Best Products are Available</h3>
        </div>      
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div><br>
<div class="clearfix"></div>

app/views/home/_testmonial.html.erb
<div class="container text-center">
<h3>Our Users Says Aboutus</h3><br>
        <div id="tcb-testimonial-carousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#tcb-testimonial-carousel" data-slide-to="0" class="active"></li>
                <li data-target="#tcb-testimonial-carousel" data-slide-to="1"></li>
                <li data-target="#tcb-testimonial-carousel" data-slide-to="2"></li>
            </ol>
            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                <div class="item active">
                    <div class="row">
                        <div class="col-xs-12">
                           <figure class="clearfix">
                               <div class="col-md-2 col-sm-2 col-xs-12"><img class="img-responsive media-object" src="https://s3.amazonaws.com/uifaces/faces/twitter/mantia/128.jpg"> </div>
                               <div class="col-md-10 col-sm-10 col-xs-12">
                                    <figcaption class="caption">
                                        <p class="text-brand lead no-margin">Subject</p>
                                        <p><span class="glyphicon glyphicon-thumbs-up"></span> Description</p>
                                        <blockquote class="no-margin">
                                            <p>Someone Famous</p> <small><cite title="Source Title"><i class="glyphicon glyphicon-globe"></i> www.example1.com</cite></small> </blockquote>
                                    </figcaption>
                               </div>
                           </figure>
                        </div>
                    </div>
                </div>
                <%@testimonials.each do |testimonial|%>
                <div class="item">
                
                    <div class="row">
                      <div class="col-xs-12">
                        
                           <figure class="clearfix">
                               <div class="col-md-2 col-sm-2 col-xs-12"><img src="<%= testimonial.image%>" class="img-responsive media-object", style = "width = 161px;height=199px"> </div>
                               <div class="col-md-10 col-sm-10 col-xs-12">
                                    <figcaption class="caption">
                                        <p class="text-brand lead no-margin"><%=testimonial.name%></p>
                                        <p><span class="glyphicon glyphicon-thumbs-up"></span> <%=testimonial.descrition %></p>
                                        <blockquote class="no-margin">
                                            <p><%=testimonial.designation%></p> </blockquote>
                                    </figcaption>
                               </div>
                           </figure>
                           
                        </div>
                    </div>

                </div>                    <%end%>
                
            </div>
            <!-- Controls -->
            <a class="left carousel-control" href="#tcb-testimonial-carousel" data-slide="prev"> <span class="glyphicon glyphicon-chevron-left"></span> </a>
            <a class="right carousel-control" href="#tcb-testimonial-carousel" data-slide="next"> <span class="glyphicon glyphicon-chevron-right"></span> </a>
        </div>
  <br />
  
    </div>

app/views/home/_whatWe.html.erb
<div class="container text-center">    
  <h3>What We Do</h3><br>
  <div class="row">
    <div class="col-sm-12">
      <p>Lorem ipsum dolor sit amet, cum ei enim posse quaeque. Ei mea urbanitas similique. Semper dictas ornatus cum an, fugit dictas perpetua id eos, mea id omnium molestiae. Tollit mediocrem nam ei, eos aliquam deseruisse moderatius et.

Ignota laboramus ut vix, at eam odio vivendum sensibus, has novum possit te. Ex pri dicant officiis definitionem, nec et vidisse periculis patrioque, te posse possim utroque usu. Quo vitae postea disputationi at, copiosae interesset at vel. Eam paulo clita consulatu an, mel an utinam iisque ornatus, nullam inermis vivendo ad per. Ipsum dicta vituperatoribus vim in, graecis epicuri maiestatis te vim.</p>
    </div>
  </div>
</div><br>

app/views/home/checkout.html.erb
<%= render :partial => "home/slider"%>
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<div class="panel panel-info">
				<div class="panel-heading">
					<div class="panel-title">
						<div class="row">
							<div class="col-xs-6">
								<h5><span class="glyphicon glyphicon-shopping-cart"></span> Shopping Cart</h5>
							</div>
							<div class="col-xs-6">
								<!-- <button type="button" class="btn btn-primary btn-sm btn-block">
									<span class="glyphicon glyphicon-share-alt"></span> Continue shopping
								</button> -->

								<%= link_to "Continue shopping", home_deals_path ,:class => "btn btn-primary btn-sm btn-block" %>
							</div>
						</div>
					</div>
				</div>
				<div class="panel-body">
				<% if @details.count > 0%>
				<% @total = 0 %>
				<% @details.each do |f|  %>
					<div class="row">
					      <% @pdesc = Product.find(f.product_id) %>
						<div class="col-xs-2"><!-- <img class="img-responsive" src="http://placehold.it/100x70"> -->
						<%= image_tag @pdesc.image, :class => "img-responsive" %>
						</div>
						<div class="col-xs-3">
							<h4 class="product-name"><strong> <%= @pdesc.name  %> </strong></h4><h4><small><%= @pdesc.description %></small></h4>
						</div>
						<div class="col-xs-2">
							<h4 class="product-name"><strong> <%= Productcategory.find(@pdesc.product_category_id).name  %> </strong></h4>						</div>
						<div class="col-xs-2">
							<div class="col-xs-6 text-right">
								<h6><strong><%=  @pdesc.price %> </strong></h6>
								<% @total = @total + @pdesc.price  %>
							</div>
							
							<div class="col-xs-2">
								
								<%#= link_to <span class="glyphicon glyphicon-trash"> </span>.html_safe, :class => "btn btn-link btn-xs" %>
									<%= link_to "<i class='glyphicon glyphicon-trash'></i>".html_safe,   cartdel_path(f.id),:class => "btn btn-link btn-xs" %>
								
							</div>
						</div>
					</div>
					<hr>
				<% end %>
				<% else %>
					<div class="row">
						<div class="col-xs-12 text-center">
						   <p>No Products</p>
							
						</div>
						
					</div>
				<% end %>
				</div>
				<div class="panel-footer">
					<div class="row text-center">
						<div class="col-xs-9">
							<h4 class="text-right">Total <strong>$<%= @total %></strong></h4>
						</div>
						<div class="col-xs-3">
							<!-- <button type="button" class="btn btn-success btn-block">
								Checkout
							</button> -->
							<%= link_to "checkout", home_shipingAddress_path ,:class => "btn btn-success btn-block" %>	
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/home/computer_desc.html.erb
<%= render :partial => "home/slider"%>
<a href="<%= home_computers_path%>",style = "color:red">Back</a>
<div class="container-fluid bg-grey">
  <div class="row">
    <div class="col-sm-4">
      <div class="panel-body"> <img src="<%= @computer.image %>", style ="width:100%"   class="img-responsive"/><%#= image_tag "iphone5s.jpeg", :class =>"img-responsive", :style => "width:100%", :alt => "Image"%></div>
    </div>
    <div class="col-sm-8">
      <h2><%= @computer.name %></h2><br>
      <ul class="list-group">
        <li class="list-group-item">Brand  - <span><%= Brand.find(@computer.brand_id).name %></span></li> 
        <li class="list-group-item">Price - <span><%= @computer.price %>$</span></li> 
      </ul>
      <h4><strong>About Product:</strong></h4><br>
      <p><%= @computer.description %></p>
    </div>
    <div class="col-sm-4"></div>
    <div class="col-sm-8" style="text-align:right;padding: 10px; "><button type="button" class="btn btn-primary">Add to cart</button>
    <!-- <button type="button" class="btn btn-success">Checkout</button></div> -->
  </div>
  </div>
</div>

app/views/home/computers.html.erb
<%= render :partial => "home/slider"%>
<div class="container"> 
<h3>Computers</h3>   
  <div class="row">
    
    <% @computers.each do |computer|%>
    <div class="col-sm-4">
    <a href="<%=computer_desc_path(computer.id)%>">
      <div class="panel panel-primary">
        <%# @computers.each do |computer|%>
        <div class="panel-heading"><%= computer.name %></div>
        <div class="panel-body"><img src="<%= computer.image%>", class ="img-responsive", style = "width:358px;height:274px", alt = "Image"><%#= image_tag "hp.jpg", :class =>"img-responsive", :style => "width:100%", :alt => "Image"%></div>
        <div class="panel-footer"><ul class="list-group">
        <li class="list-group-item"> Brand - <span><%= Brand.find(computer.brand_id).name %></span></li>
          <li class="list-group-item"> Price - <span><%= computer.price %>$</span>
        </li>
          
        </ul>   </div>
        
        </div>
    </a>
      
    </div>
    <%end%>
    <!--  -->
  </div>
  <div class="row">
              <div class="col-xs-12" style="text-align:left;">
                <% if @computers.size > 0 %>
                  <%= will_paginate @computers %>
                <% end %>
              </div>
            </div>
</div><br><br>

app/views/home/deals.html.erb
<%= render :partial => "home/slider"%>
<div class="container">
<h3>Latest Products</h3>    
  <div class="row">
  <% @products.each do |product|%>
    <div class="col-sm-4">
    
    <a href="<%=product_desc_path(product.id)%>">
      <div class="panel panel-primary">
        <%# @products.each do |product|%>
        <div class="panel-heading"><%= product.name %></div>
        <div class="panel-body"><img src="<%= product.image%>", class ="img-responsive", style = "width:358px;height:274px", alt = "Image"><%#= image_tag "hp.jpg", :class =>"img-responsive", :style => "width:100%", :alt => "Image"%></div>
        <div class="panel-footer"><ul class="list-group">
        <li class="list-group-item"> Brand - <span><%= Brand.find(product.brand_id).name %></span></li>
          <li class="list-group-item"> Price - <span><%= product.price %>$</span>
        </li>
          
        </ul>   </div>
        
        </div>
    </a>
      
    </div>
    <%end%>
    <!--  -->
  </div>
  </div><br><br>
</div><br><br>

app/views/home/index.html.erb
<%= render :partial => "home/slider"%>
<%= render :partial => "home/whatWe"%>
<%= render :partial => "home/testmonial"%>
<div class="modal fade" id="modalsucess" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          
        </div>
        <div class="modal-body">
          <p>Your product is purchased sucessfully.</p>
        </div>
        
      </div>
      
    </div>
  </div>
  
</div>

<% if !flash[:notice].nil? %>
<script type="text/javascript">
	$(document).ready(function(){
		$("#modalsucess").modal("show");
	});
</script>
<% end %>

app/views/home/mobile_desc.html.erb
<%= render :partial => "home/slider"%>
<a href="<%=home_mobiles_path%>", style = "color:red" >Back</a>
<div class="container-fluid bg-grey">
  <div class="row">
    <div class="col-sm-4">
      <div class="panel-body"> <img src="<%= @mobile.image %>", style ="width:100%"   class="img-responsive"/><%#= image_tag "iphone5s.jpeg", :class =>"img-responsive", :style => "width:100%", :alt => "Image"%></div>
    </div>
  <%= form_tag home_cartcreate_path , :method => "get" do |f| %>
    <div class="col-sm-8">
        
      <h2><%= @mobile.name %></h2><br>
      <ul class="list-group">
        <li class="list-group-item">Brand  - <span><%= Brand.find(@mobile.brand_id).name %></span></li> 
        <li class="list-group-item">Price - <span><%= @mobile.price %>$</span></li> 
      </ul>
      <h4><strong>About Product:</strong></h4><br>
      <p><%= @mobile.description %></p>
      <%= hidden_field_tag "product_id", @mobile.id  %>
      
      <%= hidden_field_tag "user_id", current_user.id  %>
      <%= hidden_field_tag "product_category", 1  %>
    </div>
    <div class="col-sm-4"></div>
    <div class="col-sm-8" style="text-align:right;padding: 10px; ">
      <!-- <button type="button" class="btn btn-primary">Add to cart</button> -->
      <%= submit_tag "Add to cart",  :class => "btn btn-primary" %>
    <!-- <button type="button" class="btn btn-success">Checkout</button></div> -->
  </div>
<% end %>
</div>
<div class="clearfix"></div>

app/views/home/mobiles.html.erb
<%= render :partial => "home/slider"%>
<div class="container">
<h3>Mobiles</h3>    
  <div class="row">
  <% @mobiles.each do |mobile|%>
    <div class="col-sm-4">
    
    <a href="<%=mobile_desc_path(mobile.id)%>">
      <div class="panel panel-primary">
        <%# @mobiles.each do |mobile|%>
        <div class="panel-heading"><%= mobile.name %></div>
        <div class="panel-body"><img src="<%= mobile.image%>", class ="img-responsive", style = "width:358px;height:274px", alt = "Image"><%#= image_tag "hp.jpg", :class =>"img-responsive", :style => "width:100%", :alt => "Image"%></div>
        <div class="panel-footer"><ul class="list-group">
        <li class="list-group-item"> Brand - <span><%= Brand.find(mobile.brand_id).name %></span></li>
          <li class="list-group-item"> Price - <span><%= mobile.price %>$</span>
        </li>
          
        </ul>   </div>
        
        </div>
    </a>
      
    </div>
    <%end%>
    <!--  -->
  </div>
  <div class="row">
              <div class="col-xs-12" style="text-align:left;">
                <% if @mobiles.size > 0 %>
                  <%= will_paginate @mobiles %>
                <% end %>
              </div>
            </div>
</div><br><br>

app/views/home/product_desc.html.erb
<%= render :partial => "home/slider"%>
<a href="<%=home_mobiles_path%>", style = "color:red" >Back</a>
<div class="container-fluid bg-grey">
  <div class="row">
    <div class="col-sm-4">
      <div class="panel-body"> <img src="<%= @productdesc.image %>", style ="width:100%"   class="img-responsive"/><%#= image_tag "iphone5s.jpeg", :class =>"img-responsive", :style => "width:100%", :alt => "Image"%></div>
    </div>
  <%= form_tag home_cartcreate_path , :method => "get" do |f| %>
    <div class="col-sm-8">
        
      <h2><%= @productdesc.name %></h2><br>
      <ul class="list-group">
        <li class="list-group-item">Brand  - <span><%= Brand.find(@productdesc.brand_id).name %></span></li> 
        <li class="list-group-item">Price - <span><%= @productdesc.price %>$</span></li> 
      </ul>
      <h4><strong>About Product:</strong></h4><br>
      <p><%= @productdesc.description %></p>
      <%= hidden_field_tag "product_id", @productdesc.id  %>
      
      <%= hidden_field_tag "user_id", current_user.id  %>
      <%= hidden_field_tag "product_category", @productdesc.product_category_id     %>
    </div>
    <div class="col-sm-4"></div>
    <div class="col-sm-8" style="text-align:right;padding: 10px; ">
      <!-- <button type="button" class="btn btn-primary">Add to cart</button> -->
      <%= submit_tag "Add to cart",  :class => "btn btn-primary" %>
    <!-- <button type="button" class="btn btn-success">Checkout</button></div> -->
  </div>
<% end %>
</div>
<div class="clearfix"></div>

app/views/home/products.html.erb
<%= render :partial => "home/slider"%>
<div class="container">

<h3>Products</h3>    

  
        <div class="container">
  <div class="row" style="  padding-bottom: 40px;margin-left: 300px;">
    
        <div class="search" style="text-align:center">
        <%= form_tag(home_product_path, :method => "get",:class =>'form-inline', id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Product Name", :class => "form-control input-sm", :maxlength => "300", :style => "width: 500px;
  margin-left: 0px;
  height: 50px"   %>
<!-- <input type="text" class="form-control input-sm" maxlength="300" placeholder="Search" style="width: 500px;
  margin-left: 0px;
  height: 50px;" /> -->
  <%= button_tag "Search", :name => nil, :class => "btn btn-primary btn-sm"  %>
 <%end%>
</div>
  </div>
</div>

  <div class="row">
  <%  @products.each do |products|%>
    <div class="col-sm-4">
    
    <a href="<%= product_desc_path(products.id)%>">
      <div class="panel panel-primary">
        <%# @mobiles.each do |mobile|%>
        <div class="panel-heading"><%= products.name %></div>
        <div class="panel-body"><img src="<%= products.image%>", class ="img-responsive", style = "width:358px;height:274px", alt = "Image"><%#= image_tag "hp.jpg", :class =>"img-responsive", :style => "width:100%", :alt => "Image"%></div>
        <div class="panel-footer"><ul class="list-group">
        <li class="list-group-item"> Brand - <span><%= Brand.find(products.brand_id).name %></span></li>
          <li class="list-group-item"> Price - <span><%= products.price %>$</span>
        </li>
          
        </ul>   </div>
        
        </div>
    </a>
      
    </div>
    <%end%>
    <!--  -->
  </div>
  <div class="row">
              <div class="col-xs-12" style="text-align:left;">
                <% if @products.size > 0 %>
                  <%= will_paginate @products %>
                <% end %>
              </div>
            </div>
</div><br><br>
<style type="text/css">
  #search {
    
    margin-top: 0px;
    width: 250px;
}

.search {
    padding: 5px 0;
    width: 230px;
    height: 30px;
    position: relative;
    left: 10px;
    float: left;
    line-height: 22px;
}

    /*.search input {
        position: absolute;
        width: 0px;
        float: Left;
        margin-left: 210px;
        -webkit-transition: all 0.7s ease-in-out;
        -moz-transition: all 0.7s ease-in-out;
        -o-transition: all 0.7s ease-in-out;
        transition: all 0.7s ease-in-out;
        height: 30px;
        line-height: 18px;
        padding: 0 2px 0 2px;
        border-radius:1px;
    }*/

        .search:hover input, .search input:focus {
            width: 500px;
  margin-left: 0px;
  height: 50px;
        }

.btn {
    height: 30px;
    position: absolute;
    right: 0;
    top: 5px;
    border-radius:1px;
}
.btn.btn-sm {
  font-size: 12px;
  margin-right: -331px;
  height: 50px;
  width: 81px;
}

</style>

app/views/home/shipingAddress.html.erb
<div class="container">
    <div class="tag-box tag-box-v2">
                        <%= form_tag   home_product_sucess_path , :method => "get" do |f| %>
                            <div class="form-group"> <!-- Full Name -->
                                <label for="full_name_id" class="control-label">Full Name</label>
                                <input type="text" class="form-control" id="full_name_id" name="full_name" placeholder="John Deer" value=<%=  "#{@user.name}" %>>
                            </div>  

                            <div class="form-group"> <!-- Full Name -->
                                <label for="full_name_id" class="control-label">Email</label>
                                <input type="text" class="form-control" id="full_name_id" name="full_name" placeholder="John Deer" value=<%= "#{@user.email}"  %>>
                            </div>  

                            


                            <div class="form-group"> <!-- Street 1 -->
                                <label for="street1_id" class="control-label">Street Address 1</label>
                                <input type="text" class="form-control" id="street1_id" name="street1" placeholder="Street address, P.O. box, company name, c/o">
                            </div>                  
                                                    
                            <div class="form-group"> <!-- Street 2 -->
                                <label for="street2_id" class="control-label">Street Address 2</label>
                                <input type="text" class="form-control" id="street2_id" name="street2" placeholder="Apartment, suite, unit, building, floor, etc.">
                            </div>  

                            <div class="form-group"> <!-- City-->
                                <label for="city_id" class="control-label">City</label>
                                <input type="text" class="form-control" id="city_id" name="city" placeholder="Smallville">
                            </div>                                  
                                                    
                            <div class="form-group"> <!-- State Button -->
                                <label for="state_id" class="control-label">State</label>
                                <select class="form-control" id="state_id">
                                    <option value="AL">Alabama</option>
                                    <option value="AK">Alaska</option>
                                    <option value="AZ">Arizona</option>
                                    <option value="AR">Arkansas</option>
                                    <option value="CA">California</option>
                                    <option value="CO">Colorado</option>
                                    <option value="CT">Connecticut</option>
                                    <option value="DE">Delaware</option>
                                    <option value="DC">District Of Columbia</option>
                                    <option value="FL">Florida</option>
                                    <option value="GA">Georgia</option>
                                    <option value="HI">Hawaii</option>
                                    <option value="ID">Idaho</option>
                                    <option value="IL">Illinois</option>
                                    <option value="IN">Indiana</option>
                                    <option value="IA">Iowa</option>
                                    <option value="KS">Kansas</option>
                                    <option value="KY">Kentucky</option>
                                    <option value="LA">Louisiana</option>
                                    <option value="ME">Maine</option>
                                    <option value="MD">Maryland</option>
                                    <option value="MA">Massachusetts</option>
                                    <option value="MI">Michigan</option>
                                    <option value="MN">Minnesota</option>
                                    <option value="MS">Mississippi</option>
                                    <option value="MO">Missouri</option>
                                    <option value="MT">Montana</option>
                                    <option value="NE">Nebraska</option>
                                    <option value="NV">Nevada</option>
                                    <option value="NH">New Hampshire</option>
                                    <option value="NJ">New Jersey</option>
                                    <option value="NM">New Mexico</option>
                                    <option value="NY">New York</option>
                                    <option value="NC">North Carolina</option>
                                    <option value="ND">North Dakota</option>
                                    <option value="OH">Ohio</option>
                                    <option value="OK">Oklahoma</option>
                                    <option value="OR">Oregon</option>
                                    <option value="PA">Pennsylvania</option>
                                    <option value="RI">Rhode Island</option>
                                    <option value="SC">South Carolina</option>
                                    <option value="SD">South Dakota</option>
                                    <option value="TN">Tennessee</option>
                                    <option value="TX">Texas</option>
                                    <option value="UT">Utah</option>
                                    <option value="VT">Vermont</option>
                                    <option value="VA">Virginia</option>
                                    <option value="WA">Washington</option>
                                    <option value="WV">West Virginia</option>
                                    <option value="WI">Wisconsin</option>
                                    <option value="WY">Wyoming</option>
                                </select>                   
                            </div>
                            
                            <div class="form-group"> <!-- Zip Code-->
                                <label for="zip_id" class="control-label">Zip Code</label>
                                <input type="text" class="form-control" id="zip_id" name="zip" placeholder="#####">
                            </div>      
                            
                            <div class="form-group"> <!-- Submit Button -->
                                <button type="submit" class="btn btn-primary">Buy!</button>
                            </div>     
                            
                    <% end %>
                    </div>
</div>