config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :brands
  resources :productcategories
  resources :testimonials
  get 'admin/index'
  get 'admin/admin_new'
  post "admin_create" => "admin#admin_create", :as => :admin_create 
  get 'admin/user_new'
  get 'admin/orders_index'
  post "user_create" => "admin#user_create", :as => :user_create 
   get 'home/products/:id' => "home#products", :as => :home_product
  get "product_desc/:id" => "home#product_desc", :as => :product_desc
  get 'home/shipingAddress'
  get 'home/contact_us'
  post 'home/create_contactus'
  get 'home/mobiles'
  get 'home/computers'
  get 'home/product_sucess'
  post 'home/statuscreate'
  get "mobile_desc/:id" => "home#mobile_desc", :as => :mobile_desc
  get "computer_desc/:id" => "home#computer_desc", :as => :computer_desc
  get "cartdel/:id" => "home#cartdel", :as => :cartdel
   get 'admin/admin_index'
   get 'admin/user_index'
   get 'home/checkout'
   get 'home/deals'
   get 'home/cartcreate'

   root 'home#index'
   get '/signup' => 'users#new'
    post '/users' => 'users#create'

  get '/login' => 'users#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/models/product.rb
class Product < ActiveRecord::Base
	
	mount_uploader :image, ImageUploader
  validates :name, presence: true
  validates :product_category_id, presence: true
  validates :brand_id, presence: true
  validates :price, presence: true
  validates :image, presence: true
  validates :description, presence: true

	def self.search search_term
    return scoped unless search_term.present?

    if search_term =~ /\A\d+\z/ ? true : false
      
      where([' year = ? ', "#{search_term}"])
    else
      where(['name LIKE ? ', "%#{search_term}%"])
    end
    
  end
	
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  layout "admin"
  before_filter :authorize
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create

    
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      
      params.require(:product).permit(:name, :product_category_id, :brand_id, :price, :image, :description)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<script type="text/javascript">
  $(document).ready(function(){
   
   function readURL(input)
   {
      if (input.files && input.files[0]) {
          var reader = new FileReader();
          
          reader.onload = function (e) {
              $('#partimgtag').attr('src', e.target.result);
              $('#partimgtag').css("display","");
              $("#editpartimgtag").css("display","none");
          }
          
          reader.readAsDataURL(input.files[0]);
      }
    } 
   
   $("#productpart_srch_image").change(function(){
      readURL(this);
    }) ;
   $('#productpriceusd ').keyup(function(){
        // alert("hello");
        money = $("#productpriceusd").val();
        $.ajax({
            url: "<%= root_url %>/productparts/convertmoney/" + money,
            context: document.body
        }).done(function(r) {
          $("#productpriceni").val(r);
          $("#productpriceni1").val(r);
          
        });

      });

   $("#adddays").click(function(){

         $("#productpart_days").toggle();
   });
    
    
  });
    
</script>

<%= form_for(@product,:html => {:class => "form-horizontal"}) do |f| %>
<div class="box-body">
  <% if @product.errors.any? %>
     <div class="alert alert-warning alert-dismissable">
          <i class="fa fa-warning"></i>
          <button data-dismiss="alert" class="close" type="button">x</button>
      <h4><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h4>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
          <b><%= message %></b>
      
      </ul>
      <% end %>
    </div>
  <% end %>

   <div class="form-group">
        <label class="col-sm-2 control-label">Name</label>
        <div class="col-sm-8">
          <%= f.text_field :name,:class => "form-control" %>
        </div>
    </div>
  <div class="form-group">
   
    <label class="col-sm-2 control-label">Product Category</label>
    <div class="col-sm-8">
    <%= f.select :product_category_id,Productcategory.all.order("name asc").collect { |c|[c.name,c.id] },{:prompt => "Product Category"},:class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
     <label class="col-sm-2 control-label">Brand</label>
     <div class="col-sm-8">
    <%= f.select :brand_id,Brand.all.order("name asc").collect { |c|[c.name,c.id] },{:prompt => "Brand Name"},:class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Price</label>
    <div class="col-sm-8">
    <%= f.number_field :price ,:class => "form-control"%>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Image</label>
    <div class="col-sm-8">
     <img src="<%= f.object.image %>" width="100" height="100" class="thumbnail" id="partimgtag" style="display: none">
     <% if params[:action] == "edit" %>
            <img src="<%= f.object.image %>" width="100" height="100" class="thumbnail" id="editpartimgtag">
          <% end %>
    <%= f.file_field :image,:class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    
    <label class="col-sm-2 control-label">Description</label>
    <div class="col-sm-8">
    <%= f.text_area :description,:class => "form-control" %>
    </div>
  </div>
  <div class="form-group text-center">
     <button type="submit" class="btn btn-primary">Submit</button>
     <%= link_to 'Back', mobiles_path,:class =>"btn btn-primary" %> 
    
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<section class="content-header">

  <h1>Listing Products</h1>
</section>
<section class="content">
    <div class="text-centre">
      <%= link_to "Add New Product",new_product_path,:class => "btn btn-primary"%>
    </div><br/>
<div class="row">
    <div class="col-xs-12">
      <div class="box">

        <div class="box-body table-responsive">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Sno</th>
                    <th>Name</th>
                    <th>Product category</th>
                    <th>Brand</th>
                    <th>Price</th>
                    <th>Image</th>
                    <th>Description</th>
                    <th colspan="3"></th>
                  </tr>
                </thead>

                <tbody>
                  <% @a = 1 %>
                  <% @products.each do |product| %>
                    <tr>
                      <td><%= @a %></td>
                      <td><%= product.name %></td>
                        <% @name = Productcategory.find(product.product_category_id )  %>
                      <td><%= @name.name %></td>
                        <% @name = Brand.find(product.brand_id )  %>
                      <td><%= @name.name %></td>
                      <td><%= product.price %></td>
                      <td> <%= image_tag product.image, :style => "width:50px;height:50px;" %><%#= product.image %></td>
                      <td><%= product.description %></td>
                      <td>
                        <%= link_to "<i class='glyphicon glyphicon-eye-open'></i>".html_safe,  product_path(product.id),:class => " btn btn-default btn-xs" %>
                        <%= link_to "<i class='glyphicon glyphicon-pencil'></i>".html_safe, edit_product_path(product),:class => " btn btn-default btn-xs" %>
                        <!-- <%#= link_to "<i class='glyphicon glyphicon-trash'></i>".html_safe, brand_path(mobile.id),  data: { confirm: 'Are you sure?' },method: :delete,:class => " btn btn-default btn-xs" %> -->
                    </td>
                    </tr>
                    <% @a = @a + 1 %>
                  <% end %>
                </tbody>
              </table>
        </div>
      </div>
      </div>
    </div>
</section>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<section class="content-header">
  <%= link_to 'Back', products_path,:class =>"btn btn-primary pull-right" %>
  <h1>Product Details</h1>
</section>
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-body form-horizontal">
        <div class="row">
          <div class="form-group">  
            <label class="col-sm-4 text-right"><%= notice   %></label>
          </div>
          
            <div class="col-xs-8">
              <div class="form-group">  
                <label class="col-sm-4 text-right">Name:</label>
                <div class="col-sm-7">
                  <%= @product.name %>
                </div>
                </div>
                 <div class="form-group">  
                <label class="col-sm-4 text-right">Description:</label>
                <div class="col-sm-7">
                  <%= @product.description %>
                </div>
                </div>
                 <div class="form-group">  
                <label class="col-sm-4 text-right">Price:</label>
                <div class="col-sm-7">
                  <%= @product.price %>
                </div>
                </div>
                <div class="form-group">  
                <label class="col-sm-4 text-right">Product category:</label>
                <div class="col-sm-7">
                  <%= Productcategory.find(@product.product_category_id).name %>
                </div>
                </div>
                 <div class="form-group">  
                <label class="col-sm-4 text-right">Brand:</label>
                <div class="col-sm-7">
                <%= Brand.find(@product.brand_id).name %>
                  <%#= @product.name %>
                </div>
                </div>
                 <div class="form-group">  
                <label class="col-sm-4 text-right">Image:</label>
                <div class="col-sm-7">
                  <img src="<%= @product.image %>" width="100" height="100" class="thumbnail"/>
                </div>
                </div>
                
                <div class="col-sm-1">
                   <%= link_to 'Edit', edit_product_path(@product),:class =>"btn btn-primary" %>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</section>