config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :brands
  resources :productcategories
  resources :testimonials
  get 'admin/index'
  get 'admin/admin_new'
  post "admin_create" => "admin#admin_create", :as => :admin_create 
  get 'admin/user_new'
  get 'admin/orders_index'
  post "user_create" => "admin#user_create", :as => :user_create 
   get 'home/products/:id' => "home#products", :as => :home_product
  get "product_desc/:id" => "home#product_desc", :as => :product_desc
  get 'home/shipingAddress'
  get 'home/contact_us'
  post 'home/create_contactus'
  get 'home/mobiles'
  get 'home/computers'
  get 'home/product_sucess'
  post 'home/statuscreate'
  get "mobile_desc/:id" => "home#mobile_desc", :as => :mobile_desc
  get "computer_desc/:id" => "home#computer_desc", :as => :computer_desc
  get "cartdel/:id" => "home#cartdel", :as => :cartdel
   get 'admin/admin_index'
   get 'admin/user_index'
   get 'home/checkout'
   get 'home/deals'
   get 'home/cartcreate'

   root 'home#index'
   get '/signup' => 'users#new'
    post '/users' => 'users#create'

  get '/login' => 'users#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/views/layouts/_footerHome.html.erb
<footer class="container-fluid text-center">
  <p>Online Store Copyright</p>  
  <!-- <form class="form-inline">Get deals:
    <input type="email" class="form-control" size="50" placeholder="Email Address">
    <button type="button" class="btn btn-danger">Submit</button>
  </form> -->
</footer>

app/views/layouts/_ga.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-54278791-1', 'auto');
  ga('send', 'pageview');
</script>

app/views/layouts/_header.html.erb
<header class="header">
	<a href="<%= admin_index_path %>" class="logo"><%= image_tag "ElectronicsWorld-logo_03.png" %></a>
	<nav class="navbar navbar-static-top" role="navigation">
		<a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button" title="Minimize/Maximize"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </a>
		<div class="navbar-right">
			<ul class="nav navbar-nav">
				<!-- Messages: style can be found in dropdown.less-->
				<!-- User Account: style can be found in dropdown.less -->
				<li class="dropdown user user-menu">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"> <i class="fa fa-user"></i>
						<span>
							<% if current_user  %>
									<% if !current_user.name.blank? %>
										 <%= current_user.name  %>
									 <% else %>
										 <%= current_user.email  %>
									<% end %>
							<% end %>
									<i class="caret"></i>
						</span>
					</a>
					<ul class="dropdown-menu">
						<!-- User image -->
						<li class="user-header bg-light-blue">
							<%= image_tag "images.png", :class => "img-circle" %>
							<%# end %>
							<p>
								<% if current_user  %>
								<% if !current_user.name.blank? %>
									 Hello <%= current_user.name  %>
								 <% else %>
									 Hello<%= current_user.email  %>
								<% end %>
								<% end %>
								
								<!-- Jane Doe - Web Developer
								<small>Member since Nov. 2012</small> -->
							</p>
						</li>	
				
						<!-- Menu Footer-->
						<li class="user-footer">
						   <div class="pull-right">
						   <a href="<%=logout_path%>" class = "btn btn-default btn-flat">Sign out</a>
								<%#= link_to "Sign out", logout_path, :method => :delete, :class => "btn btn-default btn-flat" %>
							</div>
						</li>
					</ul>
				</li>
			</ul>
		</div>
	</nav>
</header>

app/views/layouts/_headerHome.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="<%= root_path%>"><%= image_tag "ElectronicsWorld-logo.png", :style => "margin-top: -15px;
  background-color: white;
  width: 125px;
" %></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= root_path%>">Home</a></li>
        
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Products<span class="caret"></span></a>
         <ul class="dropdown-menu">

           <% Productcategory.all.each do |f| %>
               <li><a href="<%= home_product_path(f.id)  %>"><%= f.name %></a></li>
           <% end %>
          
         
           <!-- <li><a href="#">Page 1-3</a></li> -->
         </ul>
       </li>
        <li><a href="<%=home_deals_path%>">Deals</a></li>
        <li><a href="<%=home_contact_us_path %>">Contact</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
      <li><a href="#"><span class="glyphicon glyphicon-user">Welcome <%= current_user.name.capitalize%>!</span></a></li>
      <%else%>
      <li><a href="#"data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon-user" ></span> Login</a></li>
      <%end%>
      <% if current_user %>
      <li><a href="<%=logout_path%>"><span class="">Logout</span></a></li>
      <%else%>
        <li><a href="#" data-toggle="modal" data-target="#squarespaceModal"><span>Signup</span></a></li>
      <%end%>
           <% if !session[:CART_TEMP_RANDOM].nil? %>
              <%   @count = Cart.where("tran_id = ?","#{session[:CART_TEMP_RANDOM]}").count %>
           <% else %>
               <% @count = 0 %>
           <% end %>
        <li><a href="#"><span class="glyphicon glyphicon-shopping-cart"></span> Cart (<%= @count %>)</a></li>
      </ul>
    </div>
  </div>
</nav>
<!-- ------------------login-------------------------- -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title" id="myModalLabel">Log in</h4>
      </div> <!-- /.modal-header -->

      <div class="modal-body">
        <%= form_tag '/login' do %>
          <div class="form-group">
            <div class="input-group">
            <label for="exampleInputEmail1">Name</label><br>
            <%#= text_field_tag :email %>
              <input type="text" name = "email" class="form-control" id="uLogin" placeholder="Login">
              <label for="uLogin" class="input-group-addon glyphicon glyphicon-user"></label>
            </div>
          </div> <!-- /.form-group -->

          <div class="form-group">
            <div class="input-group">
            <label for="exampleInputEmail1">Password</label><br>
            <%#= password_field_tag :password%>
              <input type="password" name="password" class="form-control" id="uPassword" placeholder="Password">
              <label for="uPassword" class="input-group-addon glyphicon glyphicon-lock"></label>
            </div> <!-- /.input-group -->
          </div> <!-- /.form-group -->

          <div class="checkbox">
            <label>
              <input type="checkbox"> Remember me
            </label>
          </div> <!-- /.checkbox -->
          

      </div> <!-- /.modal-body -->

      <div class="modal-footer">
        <button class="form-control btn btn-primary">Submit</button>
         <%end%>
        <div class="progress">
          <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="1" aria-valuemin="1" aria-valuemax="100" style="width: 0%;">
            <span class="sr-only">progress</span>
          </div>
        </div>
      </div> <!-- /.modal-footer -->

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!-- ------------------login-------------------------- -->
<!-- ------------------Signup-------------------------- -->
<!-- line modal -->
<div class="modal fade" id="squarespaceModal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
      <h4 class="modal-title" id="lineModalLabel">Sign Up</h4>
    </div>
    <div class="modal-body">
      
            <!-- content goes here -->
      <%= form_for :user, url: '/users' do |f| %>
              <div class="form-group">
                <label for="exampleInputEmail1">Name</label>
                <%= f.text_field :name, :class =>"form-control", :id =>"exampleInputEmail1", :placeholder =>"Enter Name" %>
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <%= f.text_field :email, :class =>"form-control", :id =>"exampleInputEmail1", :placeholder =>"Enter email" %>
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <%= f.password_field :password , :class =>"form-control", :id =>"exampleInputPassword1", :placeholder =>"Enter Password" %>
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Confirmation Password</label>
                <%= f.password_field :password_confirmation , :class =>"form-control", :id =>"exampleInputPassword1", :placeholder =>"Enter Confirmation Password" %>
              </div>
              <!-- <div class="form-group">
                <label for="exampleInputFile">File input</label>
                <input type="file" id="exampleInputFile">
                <p class="help-block">Example block-level help text here.</p>
              </div> -->
              <!-- <div class="checkbox">
                <label>
                  <input type="checkbox"> Check me out
                </label>
              </div> -->
              <%= f.hidden_field :role_id, :value => 2 %>
              <%= f.submit "Submit", :class =>"form-control btn btn-primary" %>
            <%end%>

    </div>
    <!-- <div class="modal-footer">
      <div class="btn-group btn-group-justified" role="group" aria-label="group button">
        <div class="btn-group" role="group">
          <button type="button" class="btn btn-default" data-dismiss="modal"  role="button">Close</button>
        </div>
        <div class="btn-group btn-delete hidden" role="group">
          <button type="button" id="delImage" class="btn btn-default btn-hover-red" data-dismiss="modal"  role="button">Delete</button>
        </div>
        <div class="btn-group" role="group">
          <button type="button" id="saveImage" class="btn btn-default btn-hover-green" data-action="save" role="button">Save</button>
        </div>
      </div>
    </div> -->
  </div>
  </div>
</div>
<!-- ------------------Signup-------------------------- -->

app/views/layouts/_sidebar.html.erb
<aside class="left-side sidebar-offcanvas">
	<!-- sidebar: style can be found in sidebar.less -->
	<section class="sidebar">
		<!-- Sidebar user panel -->
		<div class="user-panel">
				
			<div class="pull-left image">
					<%= image_tag "images.png", :class => "img-circle" %>
			</div>

			<div class="pull-left info">
			<p>
								<% if current_user  %>
								<% if !current_user.name.blank? %>
									 Hello <%= current_user.name  %>
								 <% else %>
									 Hello<%= current_user.email  %>
								<% end %>
								<% end %>
								
								<!-- Jane Doe - Web Developer
								<small>Member since Nov. 2012</small -->
							</p>
			</div>
		</div>
		<ul class="sidebar-menu">
			
						<li class="active">
							<a href="<%= admin_index_path %>"> <!--<i class="fa fa-dashboard"></i>--> <span>Dashboard</span> </a>
						</li>
						
						
	
				<li class="treeview ">
						<a href="#"><span>Users</span><i class="fa fa-angle-left pull-right"></i></a>
						<ul class="treeview-menu">
								<li class="">
										<a href="<%=admin_admin_index_path%>">  <span>Administrators</span> </a>
								</li>
								<li class="">
										<a href="<%=admin_user_index_path%>">  <span>Buyers</span> </a>
								</li>
								
						</ul>
				</li>
				<li class="treeview <%#= @active %>">
						<a href="#"><span>Database</span><i class="fa fa-angle-left pull-right"></i></a>
						<ul class="treeview-menu">
								<!-- <li class="">
						        
						        	<a href="<%#=mobiles_path%>"> <span>Mobiles</span> </a>
						       
						        </li> -->
						        <li class="">
						        	<a href="<%=brands_path%>"> <span>Brand Names</span> </a>
						        
						        </li>
						        <li class="">
						        	<a href="<%=productcategories_path%>">Product Categories</a>
						        </li>
						        <li class="">
						        	<a href="<%=testimonials_path%>"> <span>Testimonials</span> </a>
						        
						        </li>
								
				
			</ul>
			</li>
			<li class="">
							<a href="<%=products_path%>"> <!--<i class="fa fa-dashboard"></i>--> <span>Products</span></a>
							

						</li>
						<li class="">
							<a href="<%=admin_orders_index_path%>"> <!--<i class="fa fa-dashboard"></i>--> <span>Orders</span> </a>
						</li>
	</section>
</aside>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
     <title>Ecommere</title>
    <%= stylesheet_link_tag "backend", media: "all" %>
    <%= javascript_include_tag "backend"%>
    <%= csrf_meta_tags %>
    <%#= favicon_link_tag 'cp-favicon.png' %>
</head>
<body class="skin-black fixed">
  <%# if current_user %>
      <%= render :partial => "layouts/header" %>
  <%# end %>
  
  <div class="wrapper row-offcanvas row-offcanvas-left">
    <%# if current_user %>
     <%= render :partial => "layouts/sidebar"%>
    <%# end %>
    <aside class="right-side">  <!----class="right-side" firefox margin-left 220 px-->
      <% if flash[:notice] %>
        
      <% end %>
      <%= yield %>
    </aside>
  </div>
  <%= render :partial => "layouts/ga" if Rails.env=='production'%>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecommerce</title>
  <%= stylesheet_link_tag "backend", media: "all" %>
    <%= javascript_include_tag "backend"%>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default rounded borders and increase the bottom margin */ 
    .navbar {
      margin-bottom: 50px;
      border-radius: 0;
    }
    
    /* Remove the jumbotron's default bottom margin */ 
     .jumbotron {
      margin-bottom: 0;
    }
   
    /* Add a gray background color and some padding to the footer */
    footer {
	  background-color: #f2f2f2;
      padding: 25px;
    }
    /* Remove the navbar's default margin-bottom and rounded borders */ 
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }
    
    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }
    
  .carousel-inner img {
      width: 100%; /* Set width to 100% */
      margin: auto;
      min-height:200px;
  }

  /* Hide the carousel text when the screen is less than 600 pixels wide */
  @media (max-width: 600px) {
    .carousel-caption {
      display: none; 
    }
  }
  @brand-color: #b20000;
#tcb-testimonial-carousel {
    a{
        color: @brand-color;
    }
    .text-brand{
        color: @brand-color;
    }
    margin-top: 30px;
    .carousel-indicators .active {
        background: @brand-color;
    }
    .no-margin{
        margin: 0;
    }
    .carousel-indicators li {
        border: 1px solid #ccc;
    }
    .carousel-control {
        color: @brand-color;
        width: 5%;
    }
    .carousel-control:hover,
    .carousel-control:focus {
        color: @brand-color;
    }
    .carousel-control.left,
    .carousel-control.right {
        background-image: none;
    }
    .item{
        padding: 15px 40px;
        background: #f8f8f8;
    }
    .media-object {
        margin: auto;
    }
    @media screen and (max-width: 768px) {
        .media-object {
            margin-bottom: 15px;
        }
    }
}
.dropbtn {
    background-color: #4CAF50;
    color: white;
    padding: 16px;
    font-size: 16px;
    border: none;
    cursor: pointer;
}

.dropdown {
    position: relative;
    display: inline-block;
}

.dropdown-content {
    display: none;
    position: absolute;
    background-color: #f9f9f9;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
}

.dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
}

.dropdown-content a:hover {background-color: blue}

.dropdown:hover .dropdown-content {
    display: block;
}

.dropdown:hover .dropbtn {
    background-color: #3e8e41;
}
#imaginary_container{
    margin-top:20%; /* Don't copy this */
}
.stylish-input-group .input-group-addon{
    background: white !important; 
}
.stylish-input-group .form-control{
  border-right:0; 
  box-shadow:0 0 0; 
  border-color:#ccc;
}
.stylish-input-group button{
    border:0;
    background:transparent;
}
  </style>
</head>
<body>
<%= render :partial => "layouts/headerHome"%>

<%= yield %>
<%= render :partial => "layouts/footerHome"%>
</body>
</html>